<?php

namespace App\Http\Requests;

use App\Models\PaymentMode;
use Illuminate\Foundation\Http\FormRequest;

class PreinscriptionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        // Récupère le mode de paiement envoyé
        $paymentModeId = $this->input('payment_mode');
        $paymentMode = PaymentMode::findOrFail($paymentModeId);

        // Détermine si output_account est obligatoire
        $outputAccountRule = ($paymentMode->code == config('constants.payment_mode.direct'))
            ? 'nullable'
            : 'required|digits:9';
        return [
            'password' => 'required',
            'email' => 'required|email|unique:students,email',
            "city_residence" => "required|int",
            "name" => "required",
            "school_sector" => "required",
            "school_faculty" => "required|int",
            "school_level" => "required|int",
            "whatsapp_number" => "required|int|digits:9",
            "phone_number" => "required|int|digits:9",
            "relative_number" => "required|int|digits:9",
            "payment_mode" => "required|int",
            "output_account" => $outputAccountRule,
            "amount_paid" => "required|int|min:1000"
        ];
    }

    public function messages()
    {
        //return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "password.required" => "le mot de passe de votre compte utilisateur est requis",
            "email.required" => "votre email est requis",
            "email.email" => "l'entrée n est pas un email valide",
            "email.unique" => "cette email existe déjà",
            "city_residence.required" => "votre ville de résidence actuelle est requise",
            "city_residence.int" => "une erreur s'est produite dans le système",
            "name.required" => "votre nom est réquis",
            "school_sector.required" => "votre filière d'école est require",
            "school_faculty.required" => "Votre faculté est requise",
            "school_faculty.int" => "une erreur s'est produite dans le système",
            "school_level.required" => "Votre niveau d'étude est requise",
            "school_level.int" => "une erreur s'est produite dans le système",
            "whatsapp_number.required" => "Votre numero whatsapp est requis",
            "whatsapp_number.int" => "une erreur s'est produite dans le système",
            "whatsapp_number.digits" => "Numero invalide. reverifiez",
            "phone_number.required" => "Votre numero de téléphone est requis",
            "phone_number.int" => "une erreur s'est produite dans le système",
            "phone_number.digits" => "Numero invalide. revérifiez",
            "relative_number.required" => "Un numéro d'urgence est requis",
            "relative_number.int" => "une erreur s'est produite dans le système",
            "relative_number.digits" => "Numero invalide. reverifiez",
            "payment_mode.required" => "sélectionnez le moyen de paiement",
            "payment_mode.int" => "une erreur s'est produite dans le système",
            "output_account.required" => "Le numero du compte de paiement est requis",
            "output_account.int" => "une erreur s'est produite dans le système",
            "output_account.digits" => "Numero invalide. reverifiez",
            "amount_paid.required" => "le montant à débiter est requis",
            "amount_paid.int" => "une erreur s'est produite dans le système",
        ];
    }
}
